# -  /Crazy237/

FROM quay.io/crazy237/serizawa-md
RUN git clone https://github.com/Crazy237/Serizawa-Md /root/Serizawa
WORKDIR /root/Serizawa/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /Crazy237/
